Repository fga-eps-mds/2021.1-Pro-Especies-UserInterface, pull requests merged in 2021-11, with the labels that each got.

#21 E09US01 - Rascunhos
  package.json
  src/components/DraftButton/index.tsx
  src/components/DraftButton/styles.ts
  src/components/FishCard/index.tsx
  src/components/FishList/index.tsx
  src/components/FishList/styles.ts
  src/components/FishLogs/index.tsx
  src/components/FishLogs/styles.ts
  src/components/Wiki/index.tsx
  src/components/Wiki/styles.ts
  src/navigation/navigation.tsx
  src/screens/Drafts/index.tsx
  src/screens/Drafts/styles.ts
  src/screens/Maps/index.tsx
  src/screens/NewFishLog/index.tsx
  src/screens/WikiFish/index.tsx
  yarn.lock
Labels: FEATURE

#25 149 - Remoção do arredondamento na foto dos peixes
  src/components/ProfileImage/index.tsx
  src/components/ProfileImage/styles.tsx
  src/screens/WikiFish/index.tsx
Labels: bug

#26 148 - HOTFIX - Imagens na tela de listagem de biblioteca e registros não estão aparecendo
  src/components/FishCard/index.tsx
  src/components/FishCard/styles.ts
  src/components/NoFishImagePhoto/index.tsx
  src/components/NoFishImagePhoto/style.ts
  src/screens/ViewFishLog/index.tsx
  src/screens/WikiFish/index.tsx
Labels: bug

#28 E10US01 - Instruções de uso
  .gitignore
  package.json
  src/assets/InstructionsModal/Passo1.png
  src/assets/InstructionsModal/Passo1.svg
  src/components/DisableIconButton/index.tsx
  src/components/DisableIconButton/styles.ts
  src/components/InstructionsModal/index.tsx
  src/components/InstructionsModal/styles.ts
  src/components/Wiki/index.tsx
  src/contexts/authContext.tsx
  src/screens/WikiFishlogs/index.tsx
  src/screens/WikiFishlogs/styles.ts
  src/utils/getInstructionImage.tsx
  yarn.lock
Labels: FEATURE

#29 145 - HOTFIX - Correção da tela de visualização de peixes e corrigir centralização
  src/components/Property/styles.tsx
  src/navigation/navigation.tsx
  src/screens/ViewFishLog/index.tsx
  src/screens/ViewFishLog/styles.tsx
  src/screens/WikiFish/index.tsx
  src/screens/WikiFish/styles.ts
Labels: bug

#31 HOTFIX - Mudar botão dependendo do usuário que estiver logado
  src/components/FishLogs/index.tsx
  src/screens/WikiFishlogs/index.tsx
  src/services/fishLogService/exportFishLogs.ts
  yarn.lock
Labels: enhancement
